### PR TITLE
Added PDCurses Compatibility #2

### PR DESCRIPTION
**Pull request by tysenmoore-xse**
Updated PR for my PDCurses compatibility changes.  Some updates:

- Merged latest ncurses-st-menu changes (simple2, etc)
- Fixed warnings when running autogen.sh
- Fixed lib deps not getting cleared when not building PDCurses
- Removed use of BUILD_OS_WIN, now m4 check creating HAVE_LANGINFO_CODESET
- Added screenshot for X11 PDCurses
- Updates to README (updated the usage example, build info, added PDCurses specific section, etc)
- Removed the `configure` file from the repo and added to cleanconfig/.gitignore (since auto generated in autogen.sh)

### CODE REVIEW

**Comment by okbob** [comment]
I please, can you do rebase first. I cannot to merge your branch.

More I don't understand to:

<pre>
	#ifndef HAVE_LANGINFO_CODESET
	/* Don't use UTF when terminal doesn't use UTF */
	config.encoding = nl_langinfo(CODESET);
	#else
	config.encoding = "";
	#endif
</pre>

or 

<pre>
#ifndef HAVE_LANGINFO_CODESET
#include <langinfo.h>
#endif

</pre>

It looks like strage - like HAVE_LANGINFO_CODESET has negative value what it should to have.

**Comment by tysenmoore-xse** [comment]
Nice catch, very sorry.  I also did a rebase of my fork.  Not sure if there is something else I need to do to fix the conflicts.

**Comment by GitMensch** [comment]
The current state is not mergeable and would create a strange history, too.

@tysenmoore-xse I suggest to wait for @okbob to do #8, then create a complete copy of your checkout, then delete the fork, then recreate it, checkout, diff your changes in, commit, create a new "clean" PR.

**Comment by tysenmoore-xse** [comment]
That works for me.  I can wait.

**Comment by okbob** [comment]
I cleaned the projects - so please, refresh pull request

**Comment by tysenmoore-xse** [comment]
I am in the process of a new merge on a new fork.  However, I did notice you still have the configure file checked in and not part of the gitignore/cleanup.  Any specific reason?  This is a generated file and should not be checked in to avoid confusion/build problems.

**Comment by okbob** [comment]
st 26. 2. 2020 v 19:58 odesílatel Tysen Moore <notifications@github.com>
napsal:

> I am in the process of a new merge on a new fork. However, I did notice
> you still have the configure file checked in and not part of the
> gitignore/cleanup. Any specific reason? This is a generated file and should
> not be checked in to avoid confusion/build problems.
>
I know it. On almost linux system this file is same - so if I have it in
base, then lot of people doesn't need to install and run autogen.

It is very similar with Postgres  https://github.com/postgres/postgres

And I am a PostgreSQL's boy :)

Pavel

**Pull request closed without merging**
